name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev  
    steps:
    - name: Terraform Plan
      run: echo ${{ vars.AWS_REGION_LOCAL }}
    - name: Test
      run: echo ${{ secrets.AWS_REGION_LOCAL }}
